/* Per-attribute lab topologies (labs/<folder>/ in the repository), shown on each attribute's Practitioner page.
   The folder name equals the attribute id. Facts below come from each lab's README (output captured from the real lab). */
window.LEARN_LABS = {
  "01_weight": { title: "Branch with a local ISP", routers: 4,
    what: "A branch router with a local ISP link and a WAN link to HQ. At baseline it exits through HQ (shorter AS_PATH); weight makes it exit locally, and HQ-EDGE never sees the weight.",
    scenarios: [["01_weight", "SITE-R1 gives routes from its local ISP weight 300"]] },
  "02_local_pref": { title: "Dual-homed enterprise with a core router", routers: 6,
    what: "Two edges (one per ISP) and a core router with no ISP link. Local-Pref 200 on ISP-B's routes moves the whole AS, including the other edge, and the output shows the two side effects: CORE loses its alternative, and ISP-A is offered a path through you.",
    scenarios: [["02_local_pref", "EDGE2 sets Local-Pref 200 on routes from ISP-B"]] },
  "03_as_path": { title: "Two ISPs and a content network", routers: 4,
    what: "The baseline is repeatable (CONTENT breaks the tie by router-ID), so you can watch a prepend toward ISP-A move CONTENT to ISP-B, and change ISP-A's own view of the enterprise.",
    scenarios: [["03_as_path", "ENT prepends AS 65000 three extra times toward ISP-A"]] },
  "04_origin": { title: "network versus redistribute on two edges", routers: 3,
    what: "Two edges advertise the same prefix to one ISP, one with a network statement and one with redistribute static. The real '?' from redistribution demotes EDGE2; set origin igp on the redistribution lets the router-ID tie-break move the ISP to EDGE2.",
    extra: "The shared lab creates its incomplete origin with set origin incomplete. Here it comes from a real redistribute static.",
    scenarios: [["04_origin", "EDGE2 redistributes with set origin igp"]] },
  "05_med": { title: "Two links to one provider", routers: 4,
    what: "Two data centres, each linked to a different POP of the same provider AS. MED is compared between paths from one neighbor AS, so a low MED for each site's own prefix makes the provider deliver each prefix to the right site.",
    extra: "This is MED's real use. The shared lab has two different provider ASes, where MED needs always-compare-med to matter at all.",
    scenarios: [["05_med", "Each DC sends MED 50 for its own prefix and 200 for the other"]] },
  "06_next_hop": { title: "An ISP link the IGP does not know", routers: 4,
    what: "EDGE learns the route over a link that is not in the IGP, behind a route reflector. Without next-hop-self the reflector prints (inaccessible) and no best path, and the far client never learns the route.",
    scenarios: [["06_next_hop", "EDGE stops rewriting the next hop toward CORE"]] },
  "07_atomic_aggregate": { title: "A summary on one edge and not the other", routers: 5,
    what: "EDGE1 summarises into a /16 with summary-only, but EDGE2 does not, so ISP-A still hears the /24 through ISP-B. A second scenario completes the summary on EDGE2.",
    scenarios: [["07_atomic_aggregate", "EDGE1 summarises 10.10.0.0/16"], ["07_fix", "then EDGE2 summarises too (run after the first)"]] },
  "08_aggregator": { title: "Two subsidiary ASes summarised at a hub", routers: 4,
    what: "The components come from AS 65010 and AS 65020, so as-set gives a real AS_SET, the atomic flag disappears, AGGREGATOR still names the hub, and each subsidiary rejects the summary because its own AS is in it.",
    extra: "The shared lab cannot show a real AS_SET, because all its components are inside AS 65000. Here the path reads 65000 {65010,65020}.",
    scenarios: [["08_aggregator", "HQ-EDGE rebuilds the summary with as-set"]] },
  "09_community": { title: "Tagging a route toward one of two ISPs", routers: 4,
    what: "EDGE tags 10.10.0.0/16 with 65001:120 and no-export toward ISP-A. ISP-A prints the community (AA:NN) and does not pass the route on, so CONTENT hears it only through ISP-B.",
    scenarios: [["09_community", "EDGE tags the route toward ISP-A and enables send-community"]] },
  "10_originator_id": { title: "A route reflector with three clients", routers: 4,
    what: "C1 originates a prefix; the reflector stamps ORIGINATOR_ID as it reflects it to C2 and C3, and C1 itself shows none. A second scenario gives C3 the same router-ID as C1, so C3 discards the route.",
    scenarios: [["10_originator_id", "C1 advertises 10.255.99.1/32"], ["10_duplicate_id", "then C3 takes C1's router-ID (run after the first; takes about 95 seconds)"]] },
  "11_cluster_list": { title: "A two-tier reflector hierarchy", routers: 5,
    what: "RR-TOP with a regional reflector for Europe and one for the US, each with a leaf. A route crosses three reflectors and collects three cluster-IDs. Giving RR-US the same cluster-ID as RR-TOP makes the reflectors discard each other's routes, in both directions.",
    scenarios: [["11_cluster_list", "RR-US takes RR-TOP's cluster-ID"]] },
};
