/* Per-attribute lab topologies (labs/<folder>/ in the repository), shown on each attribute's Practitioner page.
   The folder name equals the attribute id. Facts below come from each lab's README (output captured from the real lab). */
window.LEARN_LABS = {
  "01_weight": { title: "Branch with a local ISP", routers: 4,
    what: "A branch router with a local ISP link and a WAN link to HQ. At baseline it exits through HQ (shorter AS_PATH); weight makes it exit locally, and HQ-EDGE never sees the weight.",
    scenarios: [["01_weight", "SITE-R1 gives routes from its local ISP weight 300"]] },
  "02_local_pref": { title: "Dual-homed enterprise with a core router", routers: 6,
    what: "Two edges (one per ISP) and a core router with no ISP link. Local-Pref 200 on ISP-B's routes moves the whole AS, including the other edge, and the output shows the two side effects: CORE loses its alternative, and ISP-A is offered a path through you.",
    scenarios: [["02_local_pref", "EDGE2 sets Local-Pref 200 on routes from ISP-B"]] },
  "03_as_path": { title: "Two ISPs and a content network", routers: 4,
    what: "The baseline is repeatable (CONTENT breaks the tie by router-ID), so you can watch a prepend toward ISP-A move CONTENT to ISP-B, and change ISP-A's own view of the enterprise.",
    scenarios: [["03_as_path", "ENT prepends AS 65000 three extra times toward ISP-A"]] },
  "04_origin": { title: "network versus redistribute on two edges", routers: 3,
    what: "Two edges advertise the same prefix to one ISP, one with a network statement and one with redistribute static. The real '?' from redistribution demotes EDGE2; set origin igp on the redistribution lets the router-ID tie-break move the ISP to EDGE2.",
    extra: "The shared lab creates its incomplete origin with set origin incomplete. Here it comes from a real redistribute static.",
    scenarios: [["04_origin", "EDGE2 redistributes with set origin igp"]] },
  "05_med": { title: "Two links to one provider", routers: 4,
    what: "Two data centres, each linked to a different POP of the same provider AS. MED is compared between paths from one neighbor AS, so a low MED for each site's own prefix makes the provider deliver each prefix to the right site.",
    extra: "This is MED's real use. The shared lab has two different provider ASes, where MED needs always-compare-med to matter at all.",
    scenarios: [["05_med", "Each DC sends MED 50 for its own prefix and 200 for the other"]] },
  "06_next_hop": { title: "An ISP link the IGP does not know", routers: 4,
    what: "EDGE learns the route over a link that is not in the IGP, behind a route reflector. Without next-hop-self the reflector prints (inaccessible) and no best path, and the far client never learns the route.",
    scenarios: [["06_next_hop", "EDGE stops rewriting the next hop toward CORE"]] },
  "07_atomic_aggregate": { title: "A summary on one edge and not the other", routers: 5,
    what: "EDGE1 summarises into a /16 with summary-only, but EDGE2 does not, so ISP-A still hears the /24 through ISP-B. A second scenario completes the summary on EDGE2.",
    scenarios: [["07_atomic_aggregate", "EDGE1 summarises 10.10.0.0/16"], ["07_fix", "then EDGE2 summarises too (run after the first)"]] },
  "08_aggregator": { title: "Two subsidiary ASes summarised at a hub", routers: 4,
    what: "The components come from AS 65010 and AS 65020, so as-set gives a real AS_SET, the atomic flag disappears, AGGREGATOR still names the hub, and each subsidiary rejects the summary because its own AS is in it.",
    extra: "The shared lab cannot show a real AS_SET, because all its components are inside AS 65000. Here the path reads 65000 {65010,65020}.",
    scenarios: [["08_aggregator", "HQ-EDGE rebuilds the summary with as-set"]] },
  "09_community": { title: "Tagging a route toward one of two ISPs", routers: 4,
    what: "EDGE tags 10.10.0.0/16 with 65001:120 and no-export toward ISP-A. ISP-A prints the community (AA:NN) and does not pass the route on, so CONTENT hears it only through ISP-B.",
    scenarios: [["09_community", "EDGE tags the route toward ISP-A and enables send-community"]] },
  "10_originator_id": { title: "A route reflector with three clients", routers: 4,
    what: "C1 originates a prefix; the reflector stamps ORIGINATOR_ID as it reflects it to C2 and C3, and C1 itself shows none. A second scenario gives C3 the same router-ID as C1, so C3 discards the route.",
    scenarios: [["10_originator_id", "C1 advertises 10.255.99.1/32"], ["10_duplicate_id", "then C3 takes C1's router-ID (run after the first; takes about 95 seconds)"]] },
  "11_cluster_list": { title: "A two-tier reflector hierarchy", routers: 5,
    what: "RR-TOP with a regional reflector for Europe and one for the US, each with a leaf. A route crosses three reflectors and collects three cluster-IDs. Giving RR-US the same cluster-ID as RR-TOP makes the reflectors discard each other's routes, in both directions.",
    scenarios: [["11_cluster_list", "RR-US takes RR-TOP's cluster-ID"]] },
  "12_mpls_l3vpn": { title: "One customer, two sites over an MPLS core", routers: 5,
    what: "CE1 - PE1 - P - PE2 - CE2. LDP labels the core, PE1 and PE2 exchange the customer's routes over iBGP address-family vpnv4 (RD and RT 65000:1), and each customer edge runs plain eBGP to its PE. The scenario mistypes PE2's import route-target: the route vanishes and the ping fails while every session stays up.",
    extra: "The P router has no BGP and no customer routes. A wrong import RT removes the prefix from the VPNv4 table completely, because a PE drops routes that no VRF imports.",
    scenarios: [["12_mpls_l3vpn", "PE2 imports route-target 65000:11 instead of 65000:1"]] },
  "13_mpls_overlap": { title: "Two customers with the same 10.1.0.0/24", routers: 7,
    what: "Customers A and B both use 10.1.0.0/24. Different RDs make two VPNv4 routes, different RTs keep each in its own VRF, and different VPN labels (19 and 20) separate the traffic. The scenario adds A's route-target to B's export list on PE2, and B's second site leaks into A's VRF and into A's router.",
    extra: "Seven routers: allow more time for bootstrap. The leak changes no session and logs nothing, which is why the RT lists need audits.",
    scenarios: [["13_mpls_overlap", "PE2 exports customer B's routes with customer A's route-target too"]] },
  "14_mpls_shared_services": { title: "Customers reach one shared service, not each other", routers: 6,
    what: "Customers A and B and a shared-services VRF at PE2. The service VRF imports both customer route-targets and exports 65000:900, and customer A already imports 900, so A reaches the service. Customer B does not yet, so the extranet is one-way. The scenario adds import 65000:900 to B's VRF and B reaches the service; A and B stay invisible to each other.",
    extra: "Both directions need an RT match. The service side (import the customer's RT) is in the baseline; the scenario adds the customer side.",
    scenarios: [["14_mpls_shared_services", "PE1 adds route-target import 65000:900 to customer B's VRF"]] },
  "15_mpls_hub_spoke": { title: "Hub and spoke through a central firewall", routers: 7,
    what: "Two spokes and a hub site behind one MPLS core. Spokes export 65000:1001 and import only the hub's 65000:1000; the hub PE has two VRFs (HUB-IN and HUB-OUT) and the firewall sends the summary 10.0.0.0/8 back. A spoke reaches the other spoke only through the hub. The scenario makes one spoke import 1001, so it learns the other spoke's /24 directly and bypasses the firewall.",
    extra: "The topology is decided by route-targets, not by cabling. Seven routers: allow more time for bootstrap.",
    scenarios: [["15_mpls_hub_spoke", "PE2 adds route-target import 65000:1001 to the SPOKE VRF"]] },
  "16_mpls_vpnv4_rr": { title: "Four PEs and one VPNv4 route reflector", routers: 7,
    what: "Four PEs peer only with a route reflector that has no VRFs (and keeps no bgp default route-target filter), so a new PE needs one session. The next hop stays the originating PE, so traffic goes PE to PE. The scenario removes route-reflector-client for PE1 and PE4: two non-clients never hear each other through the reflector, sessions stay up, and their customers lose each other.",
    extra: "On this IOS a reflector with clients kept all VPNv4 routes even with the default route-target filter on, so the lab's scenario tests client status instead. Seven routers: allow 15 minutes to bootstrap.",
    scenarios: [["16_mpls_vpnv4_rr", "RR removes route-reflector-client for PE1 and PE4"]] },
  "17_mpls_as_override": { title: "The same customer AS at both sites", routers: 5,
    what: "Both customer sites are AS 65100. The route reaches the far CE with AS_PATH 65000 65100, so it drops it as a loop while every provider check is green. Two scenarios fix it: as-override on the PEs (path 65000 65000) and allowas-in on the CEs (path 65000 65100). Each is applied on its own from the baseline.",
    extra: "Both PE-CE links use 172.16.0.0/30 (inside the VRF), so one template fits every PE and every CE.",
    scenarios: [["17_as_override", "both PEs replace the customer AS with as-override"], ["17_allowas_in", "or both CEs accept their own AS with allowas-in (run from the baseline, not after the first)"]] },
};
